version: '3.8'

services:
  mybot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    depends_on:
      - postgres
    command:
      poetry run python src/run.py
    volumes:
      - .:/app

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data\
    restart: unless-stopped
    networks:
      - postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:

networks:
  postgres: